#!/bin/sh

set -e

# Make includes.binary directory in case it doesn't exist
# Needed by steps below..
mkdir -p config/includes.binary

# Make note of build date and place i /root and on install medium
date > config/includes.chroot_after_packages/root/celleos_build_date
cp config/includes.chroot_after_packages/root/celleos_build_date config/includes.binary/

# Build user manual and place it on medium
make -C brukermanual
cp brukermanual/celleos2_brukermanual.pdf config/includes.binary/

lb build noauto "${@}"
