#!/bin/sh

set -e

make -C brukermanual clean

rm -f config/includes.chroot_after_packages/root/celleos_build_date
rm -f config/includes.binary/celleos_build_date
rm -f config/includes.binary/celleos2_brukermanual.pdf

lb clean noauto "${@}"
