#!/bin/bash

/sbin/iptables -F
/sbin/iptables -I INPUT -i lo -j ACCEPT
/sbin/iptables -I OUTPUT -o lo -j ACCEPT
/sbin/iptables -P INPUT DROP
/sbin/iptables -P OUTPUT DROP
/sbin/iptables -P FORWARD DROP

/sbin/ip6tables -F
/sbin/ip6tables -I INPUT -i lo -j ACCEPT
/sbin/ip6tables -I OUTPUT -o lo -j ACCEPT
/sbin/ip6tables -P INPUT DROP
/sbin/ip6tables -P OUTPUT DROP
/sbin/ip6tables -P FORWARD DROP
